/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c UdisksDeviceInterface -p udisksdeviceinterface udisksdeviceinterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "udisksdeviceinterface.h"

/*
 * Implementation of interface class UdisksDeviceInterface
 */

UdisksDeviceInterface::UdisksDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

UdisksDeviceInterface::~UdisksDeviceInterface()
{
}

